<a href="https://colab.research.google.com/github/Prabhjot410/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing numpy in our local system

In [40]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


used in multidimensional array. 
<li>indexed by a tuple of positive integer</li>
<li>Numpy's array is called ndarray</li>

In [41]:
import numpy as np

In [42]:
arr = np.array([[1,2,3],
                [4,5,6]], dtype='int64')

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr.shape

(2, 3)

In [45]:
arr.dtype

dtype('int64')

list in numpy

In [46]:
mylist = [[1,2,3,4],
          [5,6,7,8]]

In [47]:
myarr = np.array(mylist, dtype ='float')

In [48]:
myarr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [49]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
c = np.zeros((3,4), dtype = 'int')
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

how to set complete

In [51]:
#create an array of size 3 * 3 filled with 6s of complex type
d = np.full((3,3),6+2j,dtype ='complex')
d

array([[6.+2.j, 6.+2.j, 6.+2.j],
       [6.+2.j, 6.+2.j, 6.+2.j],
       [6.+2.j, 6.+2.j, 6.+2.j]])

In [52]:
e = np.random.random((2,2))
e

array([[0.14303256, 0.36269184],
       [0.72051593, 0.47664262]])

In [53]:
f = np.arange(0,30,2)
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

linspace : return evenly spaced values within a given interval. 

arange : step size is specfied.

In [54]:
g = np.linspace(1,5,10)
g

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [55]:
h = np.random.randint(0,10,(3,4))
h

array([[0, 7, 4, 0],
       [6, 1, 0, 6],
       [2, 9, 4, 8]])

<b>Reshaping array :</b> we can use reshape method to reshape an array. the only required condition is :     
a1*a2*a3...aN = b1*b2*b3....bM (the original size of array remains unchanged)


In [56]:
i = h.reshape(6,2)
i

array([[0, 7],
       [4, 0],
       [6, 1],
       [0, 6],
       [2, 9],
       [4, 8]])

<b>Flatten array : </b>we can use flatten method to get a copy of array collapsed into 1d.it accepts order argument.Default value is 'C' (for row major order). Use F for col major oder

In [57]:
flarr = arr.flatten(order = 'F')
flarr.shape

(6,)

In [58]:
flarr

array([1, 4, 2, 5, 3, 6])

In [59]:
flarr.T

array([1, 4, 2, 5, 3, 6])

Array indexing

In [60]:
arr = np.array([[-1,2,0,4],
                [4,5,6,7],
                [2.6,0,7,5],
                [3,-7,4,2.0]])


In [61]:
arr.shape

(4, 4)

In [62]:
temp = arr[1:4,0:2]
temp

array([[ 4. ,  5. ],
       [ 2.6,  0. ],
       [ 3. , -7. ]])

In [65]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [66]:
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [67]:
cond = arr > 0
cond

array([[False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [69]:
temp = arr[cond]
temp

array([2. , 4. , 4. , 5. , 6. , 7. , 2.6, 7. , 5. , 3. , 4. , 2. ])

Basic Operations

In [70]:
a = np.array([1,2,5,3])

In [71]:
a+1

array([2, 3, 6, 4])

In [72]:
a-1

array([0, 1, 4, 2])

In [73]:
a*10

array([10, 20, 50, 30])

In [74]:
a**2

array([ 1,  4, 25,  9])

In [76]:
a*=2
a

array([ 4,  8, 20, 12])

In [77]:
arr = np.array([[1,5,6],
               [4,7,9],
               [3,1,9]])

In [78]:
arr.max()

9

In [81]:
arr.max(axis=1)

array([6, 9, 9])

In [82]:
arr.min(axis=0)

array([1, 1, 6])

In [83]:
arr.sum()

45

In [84]:
arr.sum(axis=1)

array([12, 20, 13])

In [85]:
arr.cumsum(axis=1)

array([[ 1,  6, 12],
       [ 4, 11, 20],
       [ 3,  4, 13]])

In [86]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[4,3],
              [2,1]])


In [87]:
a+b

array([[5, 5],
       [5, 5]])

In [88]:
a*b

array([[4, 6],
       [6, 4]])

In [89]:
a.dot(b)

array([[ 8,  5],
       [20, 13]])

Sorting array

In [90]:
a = np.array([[1,4,2],
              [3,4,6],
              [0,-1,5]])

In [91]:
np.sort(a, axis= None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [92]:
np.sort(a, axis = 1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])